### ISSUE TITLE
Fedora 34 problem

### ISSUE THREAD

**Issue by pierrehenrymuller** [sinner-/kickstart-fedora-workstation#2]
Hi,

I'm new to Fedora, but I want to make an automated installation for workstation like I made with Debian preseed.

I have tested your kickstart file with isos :
- Fedora-Workstation-Live-x86_64-34
- Fedora-Server-netinst-x86_64-34

With Fedora server netinst I have the grub menu to install and I can edit to add inst.ks=URL.ks but I have no graphic desktop at reboot, only cli.
With Fedora workstation live (I don't have find workstation netinst iso) when I put inst.ks=URL.ks, the live env is started for an installation without gnome menu or way to quit install.

Which is the good way to make an automated installation for Fedora 34 desktop?
Thanks

**Comment by sinner-** [comment]
Hi Pierre,

Sorry I should update the doc as there is no longer a Fedora Workstation netinst. I use the Fedora Workstation Live iso these days.

It's been a few weeks since I used this to install Fedora on my laptop, but it definitely works.

I've updated the `Use` section of the README below to reflect what I remember doing, can you try it now and let me know if you succeed? I'll update the README on the repository with below once you report back.

### Use
* Clone and enter this repository with:
  * `git clone https://github.com/sinner-/kickstart-fedora-workstation`.
  * `cd kickstart-fedora-workstation`.
* If you're not me you will probably want to run:
  * `sed -i 's/sina-laptop/YOUR_DESIRED_HOSTNAME/' workstation.ks`.
    * (run this command before the next one to avoid sed mixups)
  * `sed -i 's/sina/YOUR_NAME/' workstation.ks`.
  * `sed -i 's/^timezone/timezone Yourcountry\/Yourcity/' workstation.ks`.
* Run the kickstart.py script which will ask you for the user password and FDE passphrase and then launch a HTTP server:
  * `python3 kickstart.py`
* Install Fedora Workstation Live ISO to a usb with `dd if=isofile.iso of=/dev/sdx bs=1M oflag=sync status=progress`.
* Boot Fedora Workstation Live USB on the target install machine.
* At the boot screen, press ESC to stop the timer, then TAB on the "Start Fedora-Workstation-Live" entry to edit the configuration options.
* Remove the `quiet` directive from the boot string.
* Append the kickstart directive to the boot string:
  * `inst.ks=http://<WEB_SERVER_IP>:<PORT>/workstation.ks`
* Hit ENTER. Install will begin and complete without any further prompt.

**Comment by pierrehenrymuller** [comment]
Hi,
Thank you for your response and interest.
I use virtualbox for testing with the official iso (no modification), uefi boot enabled.

This days I have tested again with this :
- replace rd.live.image with inst.ks... launch graphical install but with manual actions to do
- replace quiet with inst.ks... start live graphical section without change of an live normal boot, who present to me the Welcome to Fedora and choice of Try or Install. Oh and I have clic on install to see if it need an interaction to continue and there is an message : 

Title : Configuration is not supported
Message : Kickstart is not supported on live installs. This installation will continue interactively.

In this two scenarios no http request was made to ks file, but when I do the same with server iso, the file is downloadded and installation is launched but without graphical part at reboot.

It's seems the live workstation don't use inst.ks anymore.

For the doc, to start grub edited line, it's not ENTER, who add a new line, but Ctrl+x.

**Comment by sinner-** [comment]
Very surprising/strange. My last commit date was the exact day I used it to successfully install the laptop I am typing this on, exactly 21 days ago.

I've just moved house and everything is a bit chaotic here, but give me ~24h and I will find some time to setup a virtualised test.

**Comment by pierrehenrymuller** [comment]
No problem, personnal things first :)
Thanks

**Comment by sinner-** [comment]
Hi Pierre,

Thanks for your report. I was able to reproduce this issue and can no longer kickstart an installation from the Workstation LiveCD either on virtual or physical machine.

I've lodged https://bugzilla.redhat.com/show_bug.cgi?id=2005804 to find out what's going on from Fedora Anaconda team hopefully. 

I googled the message you saw  `Kickstart is not supported on live installs. This installation will continue interactively.` and found https://lists.fedorahosted.org/pipermail/anaconda-patches/2014-January/008011.html from January 2014 so I don't think that is the cause of this new behaviour.

This will impact me personally as I have been using this method to maintain my personal machines since Fedora 23. Let's hope some info is forthcoming from Fedora team so we can get to the bottom of it. If not will have to figure out what is missing/needed to make it work from the Server netinst.

**Comment by sinner-** [comment]
Hi Pierre,

I was able to successfully kickstart a working GUI installation of Fedora 34 from the Server netinst ISO just now.

The steps are

1. From the bootscreen press `UP` to switch to the "Install Fedora 34" menu
2. Press `TAB` to edit the boot config
3. `Backspace` to remove `quiet` directive
4. Add `inst.ks=http://...` directive.
5. Hit `ENTER` to start the boot process.

You shouldn't need any newline or `Ctrl-x`.

![image](https://user-images.githubusercontent.com/6150510/133982101-77c191d9-e598-4831-8f0f-ef84bf099571.png)

Give it a shot and let me know, if you succeed I will update the README accordingly.

**Comment by pierrehenrymuller** [comment]
I have tried from the server netinst and it work for the param inst.ks.
But after the complete of the installation, there is no graphical interface and I supose that server edition have more difference with the workstation in options.

**Comment by sinner-** [comment]
Can you share the diff of any changes you've made to the kickstart file?

**Comment by pierrehenrymuller** [comment]
I have tested today and it's works with your file and server netinst.
The only changed I had made is to remove sda to have an autoselect of the main disk (nvme, ssd, sda, ...).

**Comment by pierrehenrymuller** [comment]
For me it's good, I have tested again yesterday.
There is difference between server and workstation edition in the installation? I have noticed that the wallpaper is not the same, and it looks like this change can't from your kickstart.

At the final test I have add another repo for Albert and the installation make many dot on the screen without timeout or error, it's on my side now.

I confirm that with virtualbox I need to make Ctrl + x to boot in grub menu, Enter don't work for me, but probably on real hardware it's work.

Thanks for your help, good day

**Comment by sinner-** [comment]
Glad it's working for you Pierre and hope you enjoy using Fedora, I quite like now that I have everything configured to my preference.

Re wallpaper, I intentionally don't set anything to do with individual user config via kickstart. My homedir is backed up via a `duplicity` script. The idea is that if I get a new machine or my current machine dies, I build it from scratch using this kickstart project and then restore my homedir from backup which contains all my personal settings for window manager, shell, browser, etc.

I also use the above pattern on every new Fedora release, backup my homedir, wipe the machine, reinstall from kickstart, restore my homedir.

**Comment by pierrehenrymuller** [comment]
Thanks for details, good day
